// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3jRhtnjrFaHJWfNWC1k5BV
// Component: T-WLdey8LU
import * as React from "react";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_market_v_2.module.css"; // plasmic-import: 3jRhtnjrFaHJWfNWC1k5BV/projectcss
import * as sty from "./PlasmicInputTextAreaPrimary.module.css"; // plasmic-import: T-WLdey8LU/css

export const PlasmicInputTextAreaPrimary__VariantProps = new Array("type");

export const PlasmicInputTextAreaPrimary__ArgProps = new Array();

function PlasmicInputTextAreaPrimary__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <textarea
        data-plasmic-name={"textarea"}
        data-plasmic-override={overrides.textarea}
        className={classNames(defaultcss.textarea, sty.textarea, {
          [sty.textarea__type_secondary]: hasVariant(
            variants,
            "type",
            "secondary"
          )
        })}
        placeholder={"Enter text"}
        value={""}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "textarea"],
  textarea: ["textarea"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicInputTextAreaPrimary__ArgProps,
      internalVariantPropNames: PlasmicInputTextAreaPrimary__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicInputTextAreaPrimary__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicInputTextAreaPrimary";
  } else {
    func.displayName = `PlasmicInputTextAreaPrimary.${nodeName}`;
  }
  return func;
}

export const PlasmicInputTextAreaPrimary = Object.assign(
  // Top-level PlasmicInputTextAreaPrimary renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    textarea: makeNodeComponent("textarea"),
    // Metadata about props expected for PlasmicInputTextAreaPrimary
    internalVariantProps: PlasmicInputTextAreaPrimary__VariantProps,
    internalArgProps: PlasmicInputTextAreaPrimary__ArgProps
  }
);

export default PlasmicInputTextAreaPrimary;
/* prettier-ignore-end */
