// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3jRhtnjrFaHJWfNWC1k5BV
// Component: -8KQRPGoiM
import * as React from "react";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_market_v_2.module.css"; // plasmic-import: 3jRhtnjrFaHJWfNWC1k5BV/projectcss
import * as sty from "./PlasmicTagNotification.module.css"; // plasmic-import: -8KQRPGoiM/css

export const PlasmicTagNotification__VariantProps = new Array("state", "size");

export const PlasmicTagNotification__ArgProps = new Array();

function PlasmicTagNotification__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root,
        {
          [sty.root__size__10]: hasVariant(variants, "size", "_10"),
          [sty.root__size__12]: hasVariant(variants, "size", "_12"),
          [sty.root__size__16]: hasVariant(variants, "size", "_16"),
          [sty.root__size__8]: hasVariant(variants, "size", "_8"),
          [sty.root__state_alert]: hasVariant(variants, "state", "alert"),
          [sty.root__state_urgent]: hasVariant(variants, "state", "urgent"),
          [sty.root__state_warning]: hasVariant(variants, "state", "warning")
        }
      )}
    >
      <div
        data-plasmic-name={"parent"}
        data-plasmic-override={overrides.parent}
        className={classNames(defaultcss.all, projectcss.all, sty.parent, {
          [sty.parent__size__16]: hasVariant(variants, "size", "_16"),
          [sty.parent__size__8]: hasVariant(variants, "size", "_8")
        })}
      >
        <div
          data-plasmic-name={"textContent"}
          data-plasmic-override={overrides.textContent}
          className={classNames(
            defaultcss.all,
            projectcss.all,
            defaultcss.__wab_text,
            sty.textContent,
            {
              [sty.textContent__size__10]: hasVariant(variants, "size", "_10"),
              [sty.textContent__size__12]: hasVariant(variants, "size", "_12"),
              [sty.textContent__size__16]: hasVariant(variants, "size", "_16"),
              [sty.textContent__size__8]: hasVariant(variants, "size", "_8")
            }
          )}
        >
          {"1"}
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "parent", "textContent"],
  parent: ["parent", "textContent"],
  textContent: ["textContent"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTagNotification__ArgProps,
      internalVariantPropNames: PlasmicTagNotification__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicTagNotification__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTagNotification";
  } else {
    func.displayName = `PlasmicTagNotification.${nodeName}`;
  }
  return func;
}

export const PlasmicTagNotification = Object.assign(
  // Top-level PlasmicTagNotification renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    parent: makeNodeComponent("parent"),
    textContent: makeNodeComponent("textContent"),
    // Metadata about props expected for PlasmicTagNotification
    internalVariantProps: PlasmicTagNotification__VariantProps,
    internalArgProps: PlasmicTagNotification__ArgProps
  }
);

export default PlasmicTagNotification;
/* prettier-ignore-end */
