// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3jRhtnjrFaHJWfNWC1k5BV
// Component: 9E_CoFdNxe
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_market_v_2.module.css"; // plasmic-import: 3jRhtnjrFaHJWfNWC1k5BV/projectcss
import * as sty from "./PlasmicTablePricingElementPercentValueBold.module.css"; // plasmic-import: 9E_CoFdNxe/css
import Icon164Icon from "./icons/PlasmicIcon__Icon164"; // plasmic-import: ly7C2Lrvqk/icon

export const PlasmicTablePricingElementPercentValueBold__VariantProps =
  new Array();

export const PlasmicTablePricingElementPercentValueBold__ArgProps = new Array(
  "textValueProposition",
  "percent",
  "numberValue",
  "svgIcon"
);

function PlasmicTablePricingElementPercentValueBold__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"svgIconParent"}
        data-plasmic-override={overrides.svgIconParent}
        className={classNames(defaultcss.all, sty.svgIconParent)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <Icon164Icon
              className={classNames(defaultcss.all, sty.svg___9Xm3I)}
              role={"img"}
            />
          ),

          value: args.svgIcon
        })}
      </div>

      <p.Stack
        as={"div"}
        data-plasmic-name={"numberValuePercentParent"}
        data-plasmic-override={overrides.numberValuePercentParent}
        hasGap={true}
        className={classNames(defaultcss.all, sty.numberValuePercentParent)}
      >
        <div
          data-plasmic-name={"numberValueParent"}
          data-plasmic-override={overrides.numberValueParent}
          className={classNames(defaultcss.all, sty.numberValueParent)}
        >
          {p.renderPlasmicSlot({
            defaultContents: "0",
            value: args.numberValue,
            className: classNames(sty.slotNumberValue)
          })}
        </div>

        <div
          data-plasmic-name={"percentParent"}
          data-plasmic-override={overrides.percentParent}
          className={classNames(defaultcss.all, sty.percentParent)}
        >
          {p.renderPlasmicSlot({
            defaultContents: "%",
            value: args.percent,
            className: classNames(sty.slotPercent)
          })}
        </div>
      </p.Stack>

      <div
        data-plasmic-name={"textValuePropositionParent"}
        data-plasmic-override={overrides.textValuePropositionParent}
        className={classNames(defaultcss.all, sty.textValuePropositionParent)}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Payment processing fees",
          value: args.textValueProposition,
          className: classNames(sty.slotTextValueProposition)
        })}
      </div>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "svgIconParent",
    "numberValuePercentParent",
    "numberValueParent",
    "percentParent",
    "textValuePropositionParent"
  ],

  svgIconParent: ["svgIconParent"],
  numberValuePercentParent: [
    "numberValuePercentParent",
    "numberValueParent",
    "percentParent"
  ],

  numberValueParent: ["numberValueParent"],
  percentParent: ["percentParent"],
  textValuePropositionParent: ["textValuePropositionParent"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames:
        PlasmicTablePricingElementPercentValueBold__ArgProps,
      internalVariantPropNames:
        PlasmicTablePricingElementPercentValueBold__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicTablePricingElementPercentValueBold__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTablePricingElementPercentValueBold";
  } else {
    func.displayName = `PlasmicTablePricingElementPercentValueBold.${nodeName}`;
  }
  return func;
}

export const PlasmicTablePricingElementPercentValueBold = Object.assign(
  // Top-level PlasmicTablePricingElementPercentValueBold renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svgIconParent: makeNodeComponent("svgIconParent"),
    numberValuePercentParent: makeNodeComponent("numberValuePercentParent"),
    numberValueParent: makeNodeComponent("numberValueParent"),
    percentParent: makeNodeComponent("percentParent"),
    textValuePropositionParent: makeNodeComponent("textValuePropositionParent"),
    // Metadata about props expected for PlasmicTablePricingElementPercentValueBold
    internalVariantProps:
      PlasmicTablePricingElementPercentValueBold__VariantProps,
    internalArgProps: PlasmicTablePricingElementPercentValueBold__ArgProps
  }
);

export default PlasmicTablePricingElementPercentValueBold;
/* prettier-ignore-end */
