// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3jRhtnjrFaHJWfNWC1k5BV
// Component: CqX-cwjNXm
import * as React from "react";
import Head from "next/head";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import NavbarInternal from "../../NavbarInternal"; // plasmic-import: BXWgCr5-vns/component
import CardHeaderTitleDisplay from "../../CardHeaderTitleDisplay"; // plasmic-import: 1wS8JpmDTD/component
import ChipUserProfile from "../../ChipUserProfile"; // plasmic-import: 0x8Ex9CEDPX/component
import CardServiceDisplay from "../../CardServiceDisplay"; // plasmic-import: 82Lpaa43lIc/component
import FooterB from "../../FooterB"; // plasmic-import: kxeO2gTzwxU/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_market_v_2.module.css"; // plasmic-import: 3jRhtnjrFaHJWfNWC1k5BV/projectcss
import * as sty from "./PlasmicMarket.module.css"; // plasmic-import: CqX-cwjNXm/css

export const PlasmicMarket__VariantProps = new Array();

export const PlasmicMarket__ArgProps = new Array();

function PlasmicMarket__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
        <meta key="og:title" property="og:title" content={""} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavbarInternal
            data-plasmic-name={"navbarInternal"}
            data-plasmic-override={overrides.navbarInternal}
            className={classNames("__wab_instance", sty.navbarInternal)}
          />

          <div
            data-plasmic-name={"sectionMarketHeadline"}
            data-plasmic-override={overrides.sectionMarketHeadline}
            className={classNames(defaultcss.all, sty.sectionMarketHeadline)}
          >
            <CardHeaderTitleDisplay
              className={classNames(
                "__wab_instance",
                sty.cardHeaderTitleDisplay___4KxLs
              )}
              headings={[]}
              size={"_360"}
              slot={"Services"}
              textDisplay={"Market"}
              textSubhead={
                "Discover unique services to start, launch, and grow your business."
              }
            />
          </div>

          <p.Stack
            as={"div"}
            data-plasmic-name={"sectionNewServiceListings"}
            data-plasmic-override={overrides.sectionNewServiceListings}
            hasGap={true}
            className={classNames(
              defaultcss.all,
              sty.sectionNewServiceListings
            )}
          >
            <CardHeaderTitleDisplay
              className={classNames(
                "__wab_instance",
                sty.cardHeaderTitleDisplay__upcyJ
              )}
              headings={["title"]}
              slot={
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__o0Huz
                  )}
                >
                  {"New partners"}
                </div>
              }
              textSubhead={
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__wxNnk
                  )}
                >
                  {"Who's new and who's hot within the commmunity."}
                </div>
              }
            />

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__x52DM)}
            >
              <CardHeaderTitleDisplay
                className={classNames(
                  "__wab_instance",
                  sty.cardHeaderTitleDisplay__lJkoc
                )}
                headings={["title", "headline"]}
                textSubhead={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox___8Qeyr
                    )}
                  >
                    {"Rising stars"}
                  </div>
                }
              />

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__peEx)}
              >
                <ChipUserProfile
                  attributes={["rating"]}
                  className={classNames(
                    "__wab_instance",
                    sty.chipUserProfile__vfPin
                  )}
                />

                <ChipUserProfile
                  attributes={["rating"]}
                  className={classNames(
                    "__wab_instance",
                    sty.chipUserProfile__yC5Q
                  )}
                />

                <ChipUserProfile
                  attributes={["rating"]}
                  className={classNames(
                    "__wab_instance",
                    sty.chipUserProfile__nYv9M
                  )}
                />

                <ChipUserProfile
                  attributes={["rating"]}
                  className={classNames(
                    "__wab_instance",
                    sty.chipUserProfile__p7NC1
                  )}
                />

                <ChipUserProfile
                  attributes={["rating"]}
                  className={classNames(
                    "__wab_instance",
                    sty.chipUserProfile__y4Bgq
                  )}
                />

                <ChipUserProfile
                  attributes={["rating"]}
                  className={classNames(
                    "__wab_instance",
                    sty.chipUserProfile__d3Fre
                  )}
                />
              </p.Stack>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__srTxr)}
            >
              <CardHeaderTitleDisplay
                className={classNames(
                  "__wab_instance",
                  sty.cardHeaderTitleDisplay__iXeRc
                )}
                headings={["title", "headline"]}
                textSubhead={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox___6My62
                    )}
                  >
                    {"New & noteworthy"}
                  </div>
                }
              />

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__lvgDe)}
              >
                <ChipUserProfile
                  attributes={["rating"]}
                  className={classNames(
                    "__wab_instance",
                    sty.chipUserProfile__gt6Lx
                  )}
                />

                <ChipUserProfile
                  attributes={["rating"]}
                  className={classNames(
                    "__wab_instance",
                    sty.chipUserProfile__snr8T
                  )}
                />

                <ChipUserProfile
                  attributes={["rating"]}
                  className={classNames(
                    "__wab_instance",
                    sty.chipUserProfile__igvfR
                  )}
                />

                <ChipUserProfile
                  attributes={["rating"]}
                  className={classNames(
                    "__wab_instance",
                    sty.chipUserProfile___4FYl2
                  )}
                />

                <ChipUserProfile
                  attributes={["rating"]}
                  className={classNames(
                    "__wab_instance",
                    sty.chipUserProfile__z0VpV
                  )}
                />

                <ChipUserProfile
                  attributes={["rating"]}
                  className={classNames(
                    "__wab_instance",
                    sty.chipUserProfile__u8Eow
                  )}
                />
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <p.Stack
            as={"div"}
            data-plasmic-name={"sectionServiceCollections"}
            data-plasmic-override={overrides.sectionServiceCollections}
            hasGap={true}
            className={classNames(
              defaultcss.all,
              sty.sectionServiceCollections
            )}
          >
            <CardHeaderTitleDisplay
              className={classNames(
                "__wab_instance",
                sty.cardHeaderTitleDisplay__cl1Xg
              )}
              headings={["title"]}
              slot={
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__aQfy5
                  )}
                >
                  {"Personalised selection"}
                </div>
              }
              textSubhead={
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__jptVr
                  )}
                >
                  {
                    "A selection based on your search history, saves, and purchases and member profile."
                  }
                </div>
              }
            />

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__zh2Ma)}
            >
              <CardServiceDisplay
                boost={"boost"}
                className={classNames(
                  "__wab_instance",
                  sty.cardServiceDisplay__dCuvl
                )}
                membership={"membership"}
                price={"price"}
                rating={"rating"}
                size={"_270X270"}
                userStats={"userStats"}
                verification={"verification"}
              />

              <CardServiceDisplay
                boost={"boost"}
                className={classNames(
                  "__wab_instance",
                  sty.cardServiceDisplay___5EKaS
                )}
                membership={"membership"}
                price={"price"}
                rating={"rating"}
                size={"_270X270"}
                userStats={"userStats"}
                verification={"verification"}
              />

              <CardServiceDisplay
                boost={"boost"}
                className={classNames(
                  "__wab_instance",
                  sty.cardServiceDisplay__gzf4J
                )}
                membership={"membership"}
                price={"price"}
                rating={"rating"}
                size={"_270X270"}
                userStats={"userStats"}
                verification={"verification"}
              />

              <CardServiceDisplay
                boost={"boost"}
                className={classNames(
                  "__wab_instance",
                  sty.cardServiceDisplay__gJuf4
                )}
                membership={"membership"}
                price={"price"}
                rating={"rating"}
                size={"_270X270"}
                userStats={"userStats"}
                verification={"verification"}
              />

              <CardServiceDisplay
                boost={"boost"}
                className={classNames(
                  "__wab_instance",
                  sty.cardServiceDisplay___8SknD
                )}
                membership={"membership"}
                price={"price"}
                rating={"rating"}
                size={"_270X270"}
                userStats={"userStats"}
                verification={"verification"}
              />

              <CardServiceDisplay
                boost={"boost"}
                className={classNames(
                  "__wab_instance",
                  sty.cardServiceDisplay___33U9V
                )}
                membership={"membership"}
                price={"price"}
                rating={"rating"}
                size={"_270X270"}
                userStats={"userStats"}
                verification={"verification"}
              />
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__eMg8J)}
            >
              <CardHeaderTitleDisplay
                className={classNames(
                  "__wab_instance",
                  sty.cardHeaderTitleDisplay___9X2Sf
                )}
                headings={["title"]}
                slot={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__xSg2B
                    )}
                  >
                    {"Popular & trending"}
                  </div>
                }
                textSubhead={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__slGcz
                    )}
                  >
                    {"See what's popular and trending across the community."}
                  </div>
                }
              />

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__jWNkd)}
              >
                <CardServiceDisplay
                  boost={"boost"}
                  className={classNames(
                    "__wab_instance",
                    sty.cardServiceDisplay__dTgHx
                  )}
                  membership={"membership"}
                  price={"price"}
                  rating={"rating"}
                  size={"_270X270"}
                  userStats={"userStats"}
                  verification={"verification"}
                />

                <CardServiceDisplay
                  boost={"boost"}
                  className={classNames(
                    "__wab_instance",
                    sty.cardServiceDisplay__xw4Zy
                  )}
                  membership={"membership"}
                  price={"price"}
                  rating={"rating"}
                  size={"_270X270"}
                  userStats={"userStats"}
                  verification={"verification"}
                />

                <CardServiceDisplay
                  boost={"boost"}
                  className={classNames(
                    "__wab_instance",
                    sty.cardServiceDisplay__pBxx9
                  )}
                  membership={"membership"}
                  price={"price"}
                  rating={"rating"}
                  size={"_270X270"}
                  userStats={"userStats"}
                  verification={"verification"}
                />

                <CardServiceDisplay
                  boost={"boost"}
                  className={classNames(
                    "__wab_instance",
                    sty.cardServiceDisplay__xNp1A
                  )}
                  membership={"membership"}
                  price={"price"}
                  rating={"rating"}
                  size={"_270X270"}
                  userStats={"userStats"}
                  verification={"verification"}
                />

                <CardServiceDisplay
                  boost={"boost"}
                  className={classNames(
                    "__wab_instance",
                    sty.cardServiceDisplay__nKpCm
                  )}
                  membership={"membership"}
                  price={"price"}
                  rating={"rating"}
                  size={"_270X270"}
                  userStats={"userStats"}
                  verification={"verification"}
                />

                <CardServiceDisplay
                  boost={"boost"}
                  className={classNames(
                    "__wab_instance",
                    sty.cardServiceDisplay__wjZ79
                  )}
                  membership={"membership"}
                  price={"price"}
                  rating={"rating"}
                  size={"_270X270"}
                  userStats={"userStats"}
                  verification={"verification"}
                />
              </p.Stack>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__w5Mqp)}
            >
              <CardHeaderTitleDisplay
                className={classNames(
                  "__wab_instance",
                  sty.cardHeaderTitleDisplay__iuvNa
                )}
                headings={["title"]}
                slot={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__aC4Uc
                    )}
                  >
                    {"Go to market fast"}
                  </div>
                }
                textSubhead={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__fGgzj
                    )}
                  >
                    {
                      "A selection of services that will help you launch your next project."
                    }
                  </div>
                }
              />

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox___9OZlj)}
              >
                <CardServiceDisplay
                  boost={"boost"}
                  className={classNames(
                    "__wab_instance",
                    sty.cardServiceDisplay__f6Doe
                  )}
                  membership={"membership"}
                  price={"price"}
                  rating={"rating"}
                  size={"_270X270"}
                  userStats={"userStats"}
                  verification={"verification"}
                />

                <CardServiceDisplay
                  boost={"boost"}
                  className={classNames(
                    "__wab_instance",
                    sty.cardServiceDisplay__peRRu
                  )}
                  membership={"membership"}
                  price={"price"}
                  rating={"rating"}
                  size={"_270X270"}
                  userStats={"userStats"}
                  verification={"verification"}
                />

                <CardServiceDisplay
                  boost={"boost"}
                  className={classNames(
                    "__wab_instance",
                    sty.cardServiceDisplay___7VoH
                  )}
                  membership={"membership"}
                  price={"price"}
                  rating={"rating"}
                  size={"_270X270"}
                  userStats={"userStats"}
                  verification={"verification"}
                />

                <CardServiceDisplay
                  boost={"boost"}
                  className={classNames(
                    "__wab_instance",
                    sty.cardServiceDisplay__cCsjo
                  )}
                  membership={"membership"}
                  price={"price"}
                  rating={"rating"}
                  size={"_270X270"}
                  userStats={"userStats"}
                  verification={"verification"}
                />

                <CardServiceDisplay
                  boost={"boost"}
                  className={classNames(
                    "__wab_instance",
                    sty.cardServiceDisplay__mJx70
                  )}
                  membership={"membership"}
                  price={"price"}
                  rating={"rating"}
                  size={"_270X270"}
                  userStats={"userStats"}
                  verification={"verification"}
                />

                <CardServiceDisplay
                  boost={"boost"}
                  className={classNames(
                    "__wab_instance",
                    sty.cardServiceDisplay__cu5Yk
                  )}
                  membership={"membership"}
                  price={"price"}
                  rating={"rating"}
                  size={"_270X270"}
                  userStats={"userStats"}
                  verification={"verification"}
                />
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <FooterB
            data-plasmic-name={"footerB"}
            data-plasmic-override={overrides.footerB}
            className={classNames("__wab_instance", sty.footerB)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbarInternal",
    "sectionMarketHeadline",
    "sectionNewServiceListings",
    "sectionServiceCollections",
    "footerB"
  ],

  navbarInternal: ["navbarInternal"],
  sectionMarketHeadline: ["sectionMarketHeadline"],
  sectionNewServiceListings: ["sectionNewServiceListings"],
  sectionServiceCollections: ["sectionServiceCollections"],
  footerB: ["footerB"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMarket__ArgProps,
      internalVariantPropNames: PlasmicMarket__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicMarket__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMarket";
  } else {
    func.displayName = `PlasmicMarket.${nodeName}`;
  }
  return func;
}

export const PlasmicMarket = Object.assign(
  // Top-level PlasmicMarket renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbarInternal: makeNodeComponent("navbarInternal"),
    sectionMarketHeadline: makeNodeComponent("sectionMarketHeadline"),
    sectionNewServiceListings: makeNodeComponent("sectionNewServiceListings"),
    sectionServiceCollections: makeNodeComponent("sectionServiceCollections"),
    footerB: makeNodeComponent("footerB"),
    // Metadata about props expected for PlasmicMarket
    internalVariantProps: PlasmicMarket__VariantProps,
    internalArgProps: PlasmicMarket__ArgProps
  }
);

export default PlasmicMarket;
/* prettier-ignore-end */
