// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3jRhtnjrFaHJWfNWC1k5BV
// Component: oScI7WCn2r
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import InputTextPrimary from "../../InputTextPrimary"; // plasmic-import: a2XXnCI4Ss/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as projectcss from "./plasmic_market_v_2.module.css"; // plasmic-import: 3jRhtnjrFaHJWfNWC1k5BV/projectcss
import * as sty from "./PlasmicInputTextFormSecondary.module.css"; // plasmic-import: oScI7WCn2r/css

export const PlasmicInputTextFormSecondary__VariantProps = new Array(
  "size",
  "color",
  "subhead"
);

export const PlasmicInputTextFormSecondary__ArgProps = new Array(
  "label",
  "description"
);

function PlasmicInputTextFormSecondary__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(projectcss.all, projectcss.root_reset, sty.root, {
        [sty.root__size__270]: hasVariant(variants, "size", "_270"),
        [sty.root__size__360]: hasVariant(variants, "size", "_360"),
        [sty.root__size_stretch]: hasVariant(variants, "size", "stretch")
      })}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"parent"}
        data-plasmic-override={overrides.parent}
        hasGap={true}
        className={classNames(projectcss.all, sty.parent, {
          [sty.parent__size__270]: hasVariant(variants, "size", "_270"),
          [sty.parent__size__360]: hasVariant(variants, "size", "_360"),
          [sty.parent__size__540]: hasVariant(variants, "size", "_540"),
          [sty.parent__size__720]: hasVariant(variants, "size", "_720"),
          [sty.parent__size_stretch]: hasVariant(variants, "size", "stretch")
        })}
      >
        <label
          data-plasmic-name={"headlineLabelParent"}
          data-plasmic-override={overrides.headlineLabelParent}
          className={classNames(projectcss.all, sty.headlineLabelParent, {
            [sty.headlineLabelParent__size__270]: hasVariant(
              variants,
              "size",
              "_270"
            ),

            [sty.headlineLabelParent__size_stretch]: hasVariant(
              variants,
              "size",
              "stretch"
            )
          })}
        >
          <div
            data-plasmic-name={"headlineLabel"}
            data-plasmic-override={overrides.headlineLabel}
            className={classNames(projectcss.all, sty.headlineLabel, {
              [sty.headlineLabel__size__270]: hasVariant(
                variants,
                "size",
                "_270"
              ),

              [sty.headlineLabel__size_stretch]: hasVariant(
                variants,
                "size",
                "stretch"
              )
            })}
          >
            {p.renderPlasmicSlot({
              defaultContents: "Label",
              value: args.label,
              className: classNames(sty.slotTargetLabel, {
                [sty.slotTargetLabel__color_primary]: hasVariant(
                  variants,
                  "color",
                  "primary"
                ),

                [sty.slotTargetLabel__size_stretch]: hasVariant(
                  variants,
                  "size",
                  "stretch"
                )
              })
            })}
          </div>
        </label>

        <InputTextPrimary
          data-plasmic-name={"inputTextPrimary"}
          data-plasmic-override={overrides.inputTextPrimary}
          className={classNames("__wab_instance", sty.inputTextPrimary, {
            [sty.inputTextPrimary__color_primary]: hasVariant(
              variants,
              "color",
              "primary"
            ),

            [sty.inputTextPrimary__color_secondary]: hasVariant(
              variants,
              "color",
              "secondary"
            ),

            [sty.inputTextPrimary__color_underline]: hasVariant(
              variants,
              "color",
              "underline"
            ),

            [sty.inputTextPrimary__size__160]: hasVariant(
              variants,
              "size",
              "_160"
            ),

            [sty.inputTextPrimary__size__180]: hasVariant(
              variants,
              "size",
              "_180"
            ),

            [sty.inputTextPrimary__size__270]: hasVariant(
              variants,
              "size",
              "_270"
            ),

            [sty.inputTextPrimary__size__360]: hasVariant(
              variants,
              "size",
              "_360"
            ),

            [sty.inputTextPrimary__size__540]: hasVariant(
              variants,
              "size",
              "_540"
            ),

            [sty.inputTextPrimary__size__720]: hasVariant(
              variants,
              "size",
              "_720"
            ),

            [sty.inputTextPrimary__size_stretch]: hasVariant(
              variants,
              "size",
              "stretch"
            )
          })}
          type={
            hasVariant(variants, "color", "secondary")
              ? "secondary"
              : hasVariant(variants, "color", "primary")
              ? "primary"
              : hasVariant(variants, "color", "underline")
              ? "underline"
              : undefined
          }
          width={
            hasVariant(variants, "size", "stretch")
              ? "stretch"
              : hasVariant(variants, "size", "_720")
              ? "_720"
              : hasVariant(variants, "size", "_540")
              ? "_540"
              : hasVariant(variants, "size", "_360")
              ? "_360"
              : hasVariant(variants, "size", "_180")
              ? "_180"
              : hasVariant(variants, "size", "_160")
              ? "_160"
              : "_270"
          }
        />

        {(hasVariant(variants, "subhead", "subhead") ? true : true) ? (
          <div
            data-plasmic-name={"descriptionParent"}
            data-plasmic-override={overrides.descriptionParent}
            className={classNames(projectcss.all, sty.descriptionParent, {
              [sty.descriptionParent__subhead]: hasVariant(
                variants,
                "subhead",
                "subhead"
              )
            })}
          >
            <div
              data-plasmic-name={"descriptionTextParent"}
              data-plasmic-override={overrides.descriptionTextParent}
              className={classNames(projectcss.all, sty.descriptionTextParent, {
                [sty.descriptionTextParent__color_secondary]: hasVariant(
                  variants,
                  "color",
                  "secondary"
                )
              })}
            >
              {p.renderPlasmicSlot({
                defaultContents: "Description",
                value: args.description,
                className: classNames(sty.slotTargetDescription, {
                  [sty.slotTargetDescription__color_primary]: hasVariant(
                    variants,
                    "color",
                    "primary"
                  ),

                  [sty.slotTargetDescription__color_underline]: hasVariant(
                    variants,
                    "color",
                    "underline"
                  ),

                  [sty.slotTargetDescription__subhead]: hasVariant(
                    variants,
                    "subhead",
                    "subhead"
                  )
                })
              })}
            </div>
          </div>
        ) : null}
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "parent",
    "headlineLabelParent",
    "headlineLabel",
    "inputTextPrimary",
    "descriptionParent",
    "descriptionTextParent"
  ],

  parent: [
    "parent",
    "headlineLabelParent",
    "headlineLabel",
    "inputTextPrimary",
    "descriptionParent",
    "descriptionTextParent"
  ],

  headlineLabelParent: ["headlineLabelParent", "headlineLabel"],
  headlineLabel: ["headlineLabel"],
  inputTextPrimary: ["inputTextPrimary"],
  descriptionParent: ["descriptionParent", "descriptionTextParent"],
  descriptionTextParent: ["descriptionTextParent"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicInputTextFormSecondary__ArgProps,
      internalVariantPropNames: PlasmicInputTextFormSecondary__VariantProps
    });

    return PlasmicInputTextFormSecondary__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicInputTextFormSecondary";
  } else {
    func.displayName = `PlasmicInputTextFormSecondary.${nodeName}`;
  }
  return func;
}

export const PlasmicInputTextFormSecondary = Object.assign(
  // Top-level PlasmicInputTextFormSecondary renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    parent: makeNodeComponent("parent"),
    headlineLabelParent: makeNodeComponent("headlineLabelParent"),
    headlineLabel: makeNodeComponent("headlineLabel"),
    inputTextPrimary: makeNodeComponent("inputTextPrimary"),
    descriptionParent: makeNodeComponent("descriptionParent"),
    descriptionTextParent: makeNodeComponent("descriptionTextParent"),
    // Metadata about props expected for PlasmicInputTextFormSecondary
    internalVariantProps: PlasmicInputTextFormSecondary__VariantProps,
    internalArgProps: PlasmicInputTextFormSecondary__ArgProps
  }
);

export default PlasmicInputTextFormSecondary;
/* prettier-ignore-end */
