// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3jRhtnjrFaHJWfNWC1k5BV
// Component: xIU_FMgFYC
import * as React from "react";
import Head from "next/head";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavbarPrimary from "../../NavbarPrimary"; // plasmic-import: Wo-euFIot3l/component
import ButtonPrimary from "../../ButtonPrimary"; // plasmic-import: koVqNkx_82/component
import PricingPageElementTeamBlock from "../../PricingPageElementTeamBlock"; // plasmic-import: XT0p4nILA-/component
import PricingPageElementServiceBlock from "../../PricingPageElementServiceBlock"; // plasmic-import: 7N2UMf446In/component
import TablePricing from "../../TablePricing"; // plasmic-import: TN5u_5IVRmW/component
import CardFeatureDescription from "../../CardFeatureDescription"; // plasmic-import: g0j2UvLSvh/component
import { useScreenVariants as useScreenVariantso9SjFZaOqjqz } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: o9sjFZaOQJQZ/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_market_v_2.module.css"; // plasmic-import: 3jRhtnjrFaHJWfNWC1k5BV/projectcss
import sty from "./PlasmicPartnerpricing.module.css"; // plasmic-import: xIU_FMgFYC/css
import LineIcon from "./icons/PlasmicIcon__Line"; // plasmic-import: fHLiNpAx_6Z/icon
import Icon129Icon from "./icons/PlasmicIcon__Icon129"; // plasmic-import: 1Q3PXgbL-f/icon
import TeamPartnersIcon from "./icons/PlasmicIcon__TeamPartners"; // plasmic-import: nykSsHgmL/icon
import Icon164Icon from "./icons/PlasmicIcon__Icon164"; // plasmic-import: ly7C2Lrvqk/icon
import Icon122Icon from "./icons/PlasmicIcon__Icon122"; // plasmic-import: 5y-W1ac1tp/icon
import ListingIcon from "./icons/PlasmicIcon__Listing"; // plasmic-import: NNbE63A0Ys/icon
import Icon169Icon from "./icons/PlasmicIcon__Icon169"; // plasmic-import: kZwjesU0eU/icon
import DesignIcon from "./icons/PlasmicIcon__Design"; // plasmic-import: l3isbgQ3dC/icon
import GlobeAmericaIcon from "./icons/PlasmicIcon__GlobeAmerica"; // plasmic-import: RRtaLxXmQA/icon
import P2PPayPaymentIcon from "./icons/PlasmicIcon__P2PPayPayment"; // plasmic-import: cymbQps3m/icon
import VerifiedIcon from "./icons/PlasmicIcon__Verified"; // plasmic-import: Vkzuz4t2NA/icon
import ChartIcon from "./icons/PlasmicIcon__Chart"; // plasmic-import: -1VBIW_pTX/icon

export const PlasmicPartnerpricing__VariantProps = new Array();

export const PlasmicPartnerpricing__ArgProps = new Array();

function PlasmicPartnerpricing__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantso9SjFZaOqjqz()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          {false ? (
            <NavbarPrimary
              data-plasmic-name={"navbarPrimary"}
              data-plasmic-override={overrides.navbarPrimary}
              className={classNames("__wab_instance", sty.navbarPrimary)}
              user={"seller"}
            />
          ) : null}

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__xw3D5)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___8NTuR
              )}
            >
              {"Grow from solopreneur to global creative force."}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__puJal
              )}
            >
              {
                "Scope and create unique offerings from our library of services, collaborate with partners, and sell directly to your followers, startups, and global brands - all over the world."
              }
            </div>

            <ButtonPrimary
              data-plasmic-name={"partnerSellingButton"}
              data-plasmic-override={overrides.partnerSellingButton}
              className={classNames("__wab_instance", sty.partnerSellingButton)}
              color={"primary"}
              width={"_360"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bCnFr
                )}
              >
                {"Start selling"}
              </div>
            </ButtonPrimary>
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__mNj8P)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"overlineHeadline"}
              data-plasmic-override={overrides.overlineHeadline}
              hasGap={true}
              className={classNames(projectcss.all, sty.overlineHeadline)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__qXrCf)}
              >
                <LineIcon
                  className={classNames(projectcss.all, sty.svg__hvInH)}
                  role={"img"}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox___24Ig5)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__e3Ga9
                    )}
                  >
                    {"Free to start"}
                  </div>
                </div>

                <LineIcon
                  className={classNames(projectcss.all, sty.svg__cuOou)}
                  role={"img"}
                />
              </p.Stack>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___6REb0
                )}
              >
                {"We grow and get better only when our partners make money."}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__prYez)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__rcvlP)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__lIpfr)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cbj2J
                    )}
                  >
                    {"Maker"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__azDnF
                    )}
                  >
                    {"Partner"}
                  </div>
                </p.Stack>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wFuH
                  )}
                >
                  {
                    "It's free to start and get everything you need to create meaningful income for your business, your collaborators, and a rewarding experience for your followers and clients."
                  }
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"partnerMakerPricingTable"}
                data-plasmic-override={overrides.partnerMakerPricingTable}
                hasGap={true}
                className={classNames(
                  projectcss.all,
                  sty.partnerMakerPricingTable
                )}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"featureParent"}
                  data-plasmic-override={overrides.featureParent}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.featureParent)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vwxfs
                    )}
                  >
                    {"features"}
                  </div>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"textIconFeature"}
                    data-plasmic-override={overrides.textIconFeature}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.textIconFeature)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wlPz)}
                    >
                      <Icon129Icon
                        className={classNames(projectcss.all, sty.svg__hgDJg)}
                        role={"img"}
                      />
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gnwu
                      )}
                    >
                      {"Get started for free"}
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"textIconFeature3"}
                    data-plasmic-override={overrides.textIconFeature3}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.textIconFeature3)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__an01O)}
                    >
                      <Icon129Icon
                        className={classNames(projectcss.all, sty.svg__k5Yt)}
                        role={"img"}
                      />
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2Xzml
                      )}
                    >
                      {"No annual fee"}
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"textIconFeature22"}
                    data-plasmic-override={overrides.textIconFeature22}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      sty.textIconFeature22
                    )}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qXBn)}
                    >
                      <Icon129Icon
                        className={classNames(projectcss.all, sty.svg___5Jdjh)}
                        role={"img"}
                      />
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__elFdi
                      )}
                    >
                      {"Hosted Partner profile"}
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"textIconFeature4"}
                    data-plasmic-override={overrides.textIconFeature4}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.textIconFeature4)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ewRxj)}
                    >
                      <Icon129Icon
                        className={classNames(projectcss.all, sty.svg__igdmc)}
                        role={"img"}
                      />
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___78O4P
                      )}
                    >
                      {"Join events & webinars"}
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"textIconFeature5"}
                    data-plasmic-override={overrides.textIconFeature5}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.textIconFeature5)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___5ZbyH
                      )}
                    >
                      <Icon129Icon
                        className={classNames(projectcss.all, sty.svg__hijmx)}
                        role={"img"}
                      />
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3JRw8
                      )}
                    >
                      {"Access community and messaging"}
                    </div>
                  </p.Stack>

                  <PricingPageElementTeamBlock
                    data-plasmic-name={"pricingPageElementTeamBlock"}
                    data-plasmic-override={
                      overrides.pricingPageElementTeamBlock
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.pricingPageElementTeamBlock
                    )}
                    slot={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zGDs
                        )}
                      >
                        {"1"}
                      </div>
                    }
                    slot2={
                      <TeamPartnersIcon
                        className={classNames(projectcss.all, sty.svg__qwFmK)}
                        role={"img"}
                      />
                    }
                    slot3={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0SwN
                        )}
                      >
                        {"Team"}
                      </div>
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__h2Lcy
                      )}
                    >
                      {"User included"}
                    </div>
                  </PricingPageElementTeamBlock>

                  <PricingPageElementServiceBlock
                    data-plasmic-name={"pricingPageElementServiceBlock"}
                    data-plasmic-override={
                      overrides.pricingPageElementServiceBlock
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.pricingPageElementServiceBlock
                    )}
                    featurevalueText={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__br3D7
                        )}
                      >
                        {"Priority upgrade per listing"}
                      </div>
                    }
                    slot={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wkLr
                        )}
                      >
                        {"8"}
                      </div>
                    }
                    slot10={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0BkM2
                        )}
                      >
                        {"Standard rate per listing"}
                      </div>
                    }
                    slot11={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kkFlc
                        )}
                      >
                        {"Payment processing fees"}
                      </div>
                    }
                    slot12={
                      <Icon164Icon
                        className={classNames(projectcss.all, sty.svg__btZgk)}
                        role={"img"}
                      />
                    }
                    slot13={
                      <Icon122Icon
                        className={classNames(projectcss.all, sty.svg___7TLq)}
                        role={"img"}
                      />
                    }
                    slot14={
                      <ListingIcon
                        className={classNames(projectcss.all, sty.svg__vWvO0)}
                        role={"img"}
                      />
                    }
                    slot15={
                      <Icon169Icon
                        className={classNames(projectcss.all, sty.svg__ia9B)}
                        role={"img"}
                      />
                    }
                    slot2={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kchUz
                        )}
                      >
                        {"5"}
                      </div>
                    }
                    slot3={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fnvBx
                        )}
                      >
                        {"3"}
                      </div>
                    }
                    slot4={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xi5G5
                        )}
                      >
                        {"Service rate on earned income"}
                      </div>
                    }
                    slot5={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jiukn
                        )}
                      >
                        {"$"}
                      </div>
                    }
                    slot6={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__igePv
                        )}
                      >
                        {"Service"}
                      </div>
                    }
                    slot7={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ePb1H
                        )}
                      >
                        {"$"}
                      </div>
                    }
                    slot8={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pMdXl
                        )}
                      >
                        {"%"}
                      </div>
                    }
                    slot9={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ezKan
                        )}
                      >
                        {"%"}
                      </div>
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6CITc
                      )}
                    >
                      {"0"}
                    </div>
                  </PricingPageElementServiceBlock>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__ytqvk)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__cDx72)}
                  >
                    <div
                      data-plasmic-name={"dollarPrice"}
                      data-plasmic-override={overrides.dollarPrice}
                      className={classNames(projectcss.all, sty.dollarPrice)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dBblD
                        )}
                      >
                        {"$"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gD8J
                        )}
                      >
                        {"0"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lr5Y
                      )}
                    >
                      {"/Year"}
                    </div>
                  </p.Stack>

                  <ButtonPrimary
                    className={classNames(
                      "__wab_instance",
                      sty.buttonPrimary__rw226
                    )}
                    color={"primary"}
                    width={"_270"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__keGh
                      )}
                    >
                      {"Start selling"}
                    </div>
                  </ButtonPrimary>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3GDyF
                    )}
                  >
                    {"No creditcard required"}
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__ndgje)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"overlineHeadline22"}
              data-plasmic-override={overrides.overlineHeadline22}
              hasGap={true}
              className={classNames(projectcss.all, sty.overlineHeadline22)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__wz9Wv)}
              >
                <LineIcon
                  className={classNames(projectcss.all, sty.svg__isDr)}
                  role={"img"}
                />

                <div className={classNames(projectcss.all, sty.freeBox__kLpgA)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__y1Qv5
                    )}
                  >
                    {"Premium Plans"}
                  </div>
                </div>

                <LineIcon
                  className={classNames(projectcss.all, sty.svg__eSZ)}
                  role={"img"}
                />
              </p.Stack>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xSr4P
                )}
              >
                {"Designed for every stage of your business growth."}
              </div>
            </p.Stack>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___58Cuj
              )}
            >
              {
                "Go from a one person creative professional to a global studio. Work from anywhere - on your terms - knowing you have a community to support you at every stage of your growth."
              }
            </div>
          </p.Stack>

          <p.Stack
            as={"div"}
            data-plasmic-name={"partnerPricingTableSection"}
            data-plasmic-override={overrides.partnerPricingTableSection}
            hasGap={true}
            className={classNames(
              projectcss.all,
              sty.partnerPricingTableSection
            )}
          >
            {true ? (
              <TablePricing
                data-plasmic-name={"partnerProPricingTable"}
                data-plasmic-override={overrides.partnerProPricingTable}
                className={classNames(
                  "__wab_instance",
                  sty.partnerProPricingTable
                )}
                slot={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hb4Af
                    )}
                  >
                    {
                      "Choose if you are an independent creative professional or solopreneur getting ready to grow your creative technology studio."
                    }
                  </div>
                }
                slot12={"Service rate on income"}
                slot14={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aeqQq
                    )}
                  >
                    {"Everything in Maker - plus"}
                  </div>
                }
                slot15={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vzHXs
                    )}
                  >
                    {"Verified profile"}
                  </div>
                }
                slot16={"Receive and respond to direct messages."}
                slot17={"Priority access to events and workshops"}
                slot18={"Email and community support"}
                slot20={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3OnAg
                    )}
                  >
                    {"Start selling"}
                  </div>
                }
                slot3={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pj7Ye
                    )}
                  >
                    {
                      "Get all the tools you need to grow a global audience and build a valuable business."
                    }
                  </div>
                }
                slot4={"2"}
                slot5={"5"}
                slot6={"3"}
                slot7={"2"}
              >
                {"Pro"}
              </TablePricing>
            ) : null}

            <TablePricing
              data-plasmic-name={"partnerStartupPricingTable"}
              data-plasmic-override={overrides.partnerStartupPricingTable}
              className={classNames(
                "__wab_instance",
                sty.partnerStartupPricingTable
              )}
              slot={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__soZsm
                  )}
                >
                  {
                    "Choose if you are scaling up your studio and want more tools to manage your business and collaborate with other teams."
                  }
                </div>
              }
              slot12={"Service rate on income"}
              slot14={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jmO9N
                  )}
                >
                  {"Everything in Pro - plus"}
                </div>
              }
              slot15={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1Jop3
                  )}
                >
                  {"Advanced partner profile"}
                </div>
              }
              slot16={"Advanced composite products & services"}
              slot17={"Subscription & promotion management tools"}
              slot18={"Chat support"}
              slot2={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jBfaa
                  )}
                >
                  {"75"}
                </div>
              }
              slot20={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6KZ0
                  )}
                >
                  {"Start selling"}
                </div>
              }
              slot3={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oaVu
                  )}
                >
                  {
                    "Form teams, collaborate, and access advanced scoping and service design tools."
                  }
                </div>
              }
              slot6={"2"}
            >
              {"Studio"}
            </TablePricing>

            <TablePricing
              data-plasmic-name={"partnerAgencyPricingtable"}
              data-plasmic-override={overrides.partnerAgencyPricingtable}
              className={classNames(
                "__wab_instance",
                sty.partnerAgencyPricingtable
              )}
              slot={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eSuWu
                  )}
                >
                  {
                    "Choose if you are a global agency that wants advanced subscription, composite services, expense management, and collaboration tools."
                  }
                </div>
              }
              slot10={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dBtJw
                  )}
                >
                  {"Free listings"}
                </div>
              }
              slot11={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xNvSn
                  )}
                >
                  {"$"}
                </div>
              }
              slot12={"No service rate on income"}
              slot13={"Payment processing fees"}
              slot14={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qwBj
                  )}
                >
                  {"Everything in Studio - plus"}
                </div>
              }
              slot15={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uaTPf
                  )}
                >
                  {"Featured partner profile"}
                </div>
              }
              slot16={"Priority access to events & workshops."}
              slot17={"Partner discount on popular Saas tools."}
              slot18={"Dedicated and private partner community."}
              slot2={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bdYey
                  )}
                >
                  {"100"}
                </div>
              }
              slot20={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iDzgz
                  )}
                >
                  {"Start selling"}
                </div>
              }
              slot3={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nyPzf
                  )}
                >
                  {
                    "Get a featured profile, priority access to community events, and partner discounts."
                  }
                </div>
              }
              slot4={"10"}
              slot5={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fJzLf
                  )}
                >
                  {"0"}
                </div>
              }
              slot6={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wkgWa
                  )}
                >
                  {"0"}
                </div>
              }
              slot7={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hmuIu
                  )}
                >
                  {"1"}
                </div>
              }
              slot8={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9X4By
                  )}
                >
                  {"$"}
                </div>
              }
              slot9={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___471ZH
                  )}
                >
                  {"Free priority placement by default"}
                </div>
              }
            >
              {"Agency"}
            </TablePricing>
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__jppWz)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"overlineHeadline2"}
              data-plasmic-override={overrides.overlineHeadline2}
              hasGap={true}
              className={classNames(projectcss.all, sty.overlineHeadline2)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__bRr8N)}
              >
                <LineIcon
                  className={classNames(projectcss.all, sty.svg__j23Tq)}
                  role={"img"}
                />

                <div className={classNames(projectcss.all, sty.freeBox__eGh7N)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gzqj2
                    )}
                  >
                    {"Benefits"}
                  </div>
                </div>

                <LineIcon
                  className={classNames(projectcss.all, sty.svg__lj7Uq)}
                  role={"img"}
                />
              </p.Stack>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xyCfg
                )}
              >
                {"All memberships include"}
              </div>
            </p.Stack>
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__nM5Y)}
          >
            <CardFeatureDescription
              className={classNames(
                "__wab_instance",
                sty.cardFeatureDescription__jzQpV
              )}
              headline={"Automated scoping & service design"}
              iconParent={
                <div className={classNames(projectcss.all, sty.freeBox__z1I9A)}>
                  <p.PlasmicIcon
                    PlasmicIconType={
                      hasVariant(globalVariants, "screen", "iphone12ProMax")
                        ? DesignIcon
                        : DesignIcon
                    }
                    className={classNames(projectcss.all, sty.svg__biheL)}
                    role={"img"}
                  />
                </div>
              }
              text={
                "Scope and create unique services, in multiple compositions, blazingly fast, making it easier for clients to buy your services."
              }
            />

            <CardFeatureDescription
              className={classNames(
                "__wab_instance",
                sty.cardFeatureDescription__z3Wte
              )}
              headline={"Sell direct to a global audience"}
              iconParent={
                <div className={classNames(projectcss.all, sty.freeBox__suBeb)}>
                  <p.PlasmicIcon
                    PlasmicIconType={
                      hasVariant(globalVariants, "screen", "iphone12ProMax")
                        ? GlobeAmericaIcon
                        : GlobeAmericaIcon
                    }
                    className={classNames(projectcss.all, sty.svg__vzVi6)}
                    role={"img"}
                  />
                </div>
              }
              text={
                "Reach a global client base and enjoy a steady flow of high-value, remote-first company clients all year round."
              }
            />

            <CardFeatureDescription
              className={classNames(
                "__wab_instance",
                sty.cardFeatureDescription__j0WfQ
              )}
              headline={"Fast International P2P payments"}
              iconParent={
                <div className={classNames(projectcss.all, sty.freeBox__q5Chp)}>
                  <P2PPayPaymentIcon
                    className={classNames(projectcss.all, sty.svg__iyhPz)}
                    role={"img"}
                  />
                </div>
              }
              text={
                "Get paid quickly and easily, even across international borders with automated invoice processing, payments, and escrow."
              }
            />

            <CardFeatureDescription
              className={classNames(
                "__wab_instance",
                sty.cardFeatureDescription__ts4YO
              )}
              headline={"Verified profiles, ratings & reviews"}
              iconParent={
                <div className={classNames(projectcss.all, sty.freeBox__aCib)}>
                  <VerifiedIcon
                    className={classNames(projectcss.all, sty.svg__sVbpm)}
                    role={"img"}
                  />
                </div>
              }
              text={
                "Become a trusted seller and drive future sales with verified reviews from top-tier enterprises."
              }
            />

            <CardFeatureDescription
              className={classNames(
                "__wab_instance",
                sty.cardFeatureDescription__kDm22
              )}
              headline={"Analytics & performance tracking"}
              iconParent={
                <div
                  className={classNames(projectcss.all, sty.freeBox___4Ad4N)}
                >
                  <ChartIcon
                    className={classNames(projectcss.all, sty.svg__oD4R)}
                    role={"img"}
                  />
                </div>
              }
              text={
                "Access powerful analytics and lead generation tools to better understand your followers, customers, and build a scalable and profitable business."
              }
            />

            <CardFeatureDescription
              className={classNames(
                "__wab_instance",
                sty.cardFeatureDescription__qMfwQ
              )}
              headline={"Community & collaboration"}
              iconParent={
                <div className={classNames(projectcss.all, sty.freeBox__kVtD)}>
                  <TeamPartnersIcon
                    className={classNames(projectcss.all, sty.svg__yyYG)}
                    role={"img"}
                  />
                </div>
              }
              text={
                "Learn from leading entrepreneurs, creatives, and cutting-edge technologists from around the world."
              }
            />
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__mZzs5)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__a1PDa)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"overlineHeadline24"}
                data-plasmic-override={overrides.overlineHeadline24}
                hasGap={true}
                className={classNames(projectcss.all, sty.overlineHeadline24)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__moLw)}
                >
                  <LineIcon
                    className={classNames(projectcss.all, sty.svg__meKzD)}
                    role={"img"}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__yo8P)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__goBcd
                      )}
                    >
                      {"Community"}
                    </div>
                  </div>

                  <LineIcon
                    className={classNames(projectcss.all, sty.svg__aigQn)}
                    role={"img"}
                  />
                </p.Stack>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__g9LgJ
                  )}
                >
                  {
                    "Join a global marketplace community built for creative entrepreneurs"
                  }
                </div>
              </p.Stack>
            </p.Stack>

            <ButtonPrimary
              className={classNames("__wab_instance", sty.buttonPrimary__tA8Ol)}
              color={"primary"}
              width={"_360"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__evsG
                )}
              >
                {"Start selling"}
              </div>
            </ButtonPrimary>
          </p.Stack>
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbarPrimary",
    "partnerSellingButton",
    "overlineHeadline",
    "partnerMakerPricingTable",
    "featureParent",
    "textIconFeature",
    "textIconFeature3",
    "textIconFeature22",
    "textIconFeature4",
    "textIconFeature5",
    "pricingPageElementTeamBlock",
    "pricingPageElementServiceBlock",
    "dollarPrice",
    "overlineHeadline22",
    "partnerPricingTableSection",
    "partnerProPricingTable",
    "partnerStartupPricingTable",
    "partnerAgencyPricingtable",
    "overlineHeadline2",
    "overlineHeadline24"
  ],

  navbarPrimary: ["navbarPrimary"],
  partnerSellingButton: ["partnerSellingButton"],
  overlineHeadline: ["overlineHeadline"],
  partnerMakerPricingTable: [
    "partnerMakerPricingTable",
    "featureParent",
    "textIconFeature",
    "textIconFeature3",
    "textIconFeature22",
    "textIconFeature4",
    "textIconFeature5",
    "pricingPageElementTeamBlock",
    "pricingPageElementServiceBlock",
    "dollarPrice"
  ],

  featureParent: [
    "featureParent",
    "textIconFeature",
    "textIconFeature3",
    "textIconFeature22",
    "textIconFeature4",
    "textIconFeature5",
    "pricingPageElementTeamBlock",
    "pricingPageElementServiceBlock"
  ],

  textIconFeature: ["textIconFeature"],
  textIconFeature3: ["textIconFeature3"],
  textIconFeature22: ["textIconFeature22"],
  textIconFeature4: ["textIconFeature4"],
  textIconFeature5: ["textIconFeature5"],
  pricingPageElementTeamBlock: ["pricingPageElementTeamBlock"],
  pricingPageElementServiceBlock: ["pricingPageElementServiceBlock"],
  dollarPrice: ["dollarPrice"],
  overlineHeadline22: ["overlineHeadline22"],
  partnerPricingTableSection: [
    "partnerPricingTableSection",
    "partnerProPricingTable",
    "partnerStartupPricingTable",
    "partnerAgencyPricingtable"
  ],

  partnerProPricingTable: ["partnerProPricingTable"],
  partnerStartupPricingTable: ["partnerStartupPricingTable"],
  partnerAgencyPricingtable: ["partnerAgencyPricingtable"],
  overlineHeadline2: ["overlineHeadline2"],
  overlineHeadline24: ["overlineHeadline24"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPartnerpricing__ArgProps,
      internalVariantPropNames: PlasmicPartnerpricing__VariantProps
    });

    return PlasmicPartnerpricing__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPartnerpricing";
  } else {
    func.displayName = `PlasmicPartnerpricing.${nodeName}`;
  }
  return func;
}

export const PlasmicPartnerpricing = Object.assign(
  // Top-level PlasmicPartnerpricing renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbarPrimary: makeNodeComponent("navbarPrimary"),
    partnerSellingButton: makeNodeComponent("partnerSellingButton"),
    overlineHeadline: makeNodeComponent("overlineHeadline"),
    partnerMakerPricingTable: makeNodeComponent("partnerMakerPricingTable"),
    featureParent: makeNodeComponent("featureParent"),
    textIconFeature: makeNodeComponent("textIconFeature"),
    textIconFeature3: makeNodeComponent("textIconFeature3"),
    textIconFeature22: makeNodeComponent("textIconFeature22"),
    textIconFeature4: makeNodeComponent("textIconFeature4"),
    textIconFeature5: makeNodeComponent("textIconFeature5"),
    pricingPageElementTeamBlock: makeNodeComponent(
      "pricingPageElementTeamBlock"
    ),

    pricingPageElementServiceBlock: makeNodeComponent(
      "pricingPageElementServiceBlock"
    ),

    dollarPrice: makeNodeComponent("dollarPrice"),
    overlineHeadline22: makeNodeComponent("overlineHeadline22"),
    partnerPricingTableSection: makeNodeComponent("partnerPricingTableSection"),
    partnerProPricingTable: makeNodeComponent("partnerProPricingTable"),
    partnerStartupPricingTable: makeNodeComponent("partnerStartupPricingTable"),
    partnerAgencyPricingtable: makeNodeComponent("partnerAgencyPricingtable"),
    overlineHeadline2: makeNodeComponent("overlineHeadline2"),
    overlineHeadline24: makeNodeComponent("overlineHeadline24"),
    // Metadata about props expected for PlasmicPartnerpricing
    internalVariantProps: PlasmicPartnerpricing__VariantProps,
    internalArgProps: PlasmicPartnerpricing__ArgProps
  }
);

export default PlasmicPartnerpricing;
/* prettier-ignore-end */
