// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3jRhtnjrFaHJWfNWC1k5BV
// Component: kVYwY70jN0
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "../market_v_2/plasmic_market_v_2.module.css"; // plasmic-import: 3jRhtnjrFaHJWfNWC1k5BV/projectcss
import sty from "./PlasmicTeamsTable.module.css"; // plasmic-import: kVYwY70jN0/css

export const PlasmicTeamsTable__VariantProps = new Array();

export const PlasmicTeamsTable__ArgProps = new Array();

function PlasmicTeamsTable__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(projectcss.all, projectcss.root_reset, sty.root)}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTeamsTable__ArgProps,
      internalVariantPropNames: PlasmicTeamsTable__VariantProps
    });

    return PlasmicTeamsTable__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTeamsTable";
  } else {
    func.displayName = `PlasmicTeamsTable.${nodeName}`;
  }
  return func;
}

export const PlasmicTeamsTable = Object.assign(
  // Top-level PlasmicTeamsTable renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicTeamsTable
    internalVariantProps: PlasmicTeamsTable__VariantProps,
    internalArgProps: PlasmicTeamsTable__ArgProps
  }
);

export default PlasmicTeamsTable;
/* prettier-ignore-end */
